---
kind: Template
apiVersion: v1
metadata:
  name: jenkins-s2i
  annotations:
    openshift.io/display-name: Jenkins S2I
    description: Jenkins S2I build config to create a Jenkins image with your configuration
      baked in.
    iconClass: icon-jenkins
    tags: instant-app,jenkins
objects:
- apiVersion: v1
  data:
    password: "${SOURCE_REPOSITORY_USERNAME}"
    username: "${SOURCE_REPOSITORY_PASSWORD}"
  kind: Secret
  metadata:
    name: gitlab-auth
  type: kubernetes.io/basic-auth
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${NAME}"
  spec:
    runPolicy: Serial
    source:
      contextDir: "${SOURCE_CONTEXT_DIR}"
      type: Git
      sourceSecret:
        name: gitlab-auth
      git:
        uri: "${SOURCE_REPOSITORY_URL}"
        ref: "${SOURCE_REPOSITORY_REF}"
      sourceSecret:
        name: gitlab-auth
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: jenkins-2-rhel7:latest
    output:
      to:
        kind: ImageStreamTag
        name: "${NAME}:latest"
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${NAME}"
    annotations:
      description: Keeps track of changes in the application image
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: jenkins-2-rhel7
  spec:
    tags:
    - name: latest
      annotations:
        openshift.io/imported-from: registry.access.redhat.com/openshift3/jenkins-2-rhel7
      from:
        kind: DockerImage
        name: registry.access.redhat.com/openshift3/jenkins-2-rhel7
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all objects and the resulting imagestream.
  required: true
  value: jenkins
- name: SOURCE_REPOSITORY_USERNAME
  displayName: SOURCE_REPOSITORY_USERNAME
  description: The name of the user to checkout code from gitlab (base64 endoded)
  required: true
  value: jenkins
- name: SOURCE_REPOSITORY_PASSWORD
  displayName: SOURCE_REPOSITORY_PASSWORD
  description: The password of the user to checkout code from gitlab (base64 endoded)
  required: true
  value: jenkins
- name: SOURCE_CONTEXT_DIR
  displayName: Git Context Directory
  description: Set this to the directory where the build information is (e.g. Dockerfile)
    if not using the default
- name: SOURCE_REPOSITORY_URL
  displayName: Git Repository URL
  description: The URL of the repository with your application source code.
  required: true
  value: https://github.com/rht-labs/openshift-jenkins-s2i-config.git
- name: SOURCE_REPOSITORY_REF
  displayName: Git Reference
  description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default (master) branch.
  value: master
labels:
  template: jenkins-s2i-template
